name: 'Slack Action'
description: 'Provides access to the Slack WebApi'
inputs:
  method:
    description: 'The slack web api method to call'
    required: false
    default: 'chat.postMessage'
  title:
    description: 'The title of the slack message'
    required: true
  channel:
    description: 'The name of the slack channel to post message'
    required: true   
  message:
    description: 'The plain text message'
    required: false
  custom-fields:
    description: 'The multi-line key:values to send in slack message'
    required: false
    default: ""   
  raw-input:
    description: 'The api method arguments. If set, all other values are ignored.'
    required: false
    default: '{}'
branding:
  icon: message-circle
  color: gray-dark
runs:
  using: 'node16'
  main: 'dist/index.js'